Update 01-vdom.md (#819)
* Update 01-vdom.md

changed `import html` to `import {html}` because the current version was throwing an error displayed in the render area: "TypeError: _preact2.default is not a function"

* Update content/en/tutorial/01-vdom.md

Co-authored-by: Jovi De Croock <decroockjovi@gmail.com>

Co-authored-by: Jovi De Croock <decroockjovi@gmail.com>