Update 01-vdom.md
changed `import html` to `import {html}` because the current version was throwing an error displayed in the render area: "TypeError: _preact2.default is not a function"